version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - ./dockers/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:3.2.6
    ports:
      - "63790:6379"
    command: redis-server --appendonly yes
    volumes:
       - ./dockers/redis/volumes:/data
  web:
    build:
      context: .
      dockerfile: ./dockers/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    depends_on:
      - db
      - redis